export const DESIGN_SIGNIN_REQUEST = 'DESIGN_SIGNIN_REQUEST';
export const DESIGN_SIGNIN_SUCCESS = 'DESIGN_SIGNIN_SUCCESS';
export const DESIGN_SIGNIN_FAIL = 'DESIGN_SIGNIN_FAIL';

export const DESIGN_UPDATE_REQUEST = 'DESIGN_UPDATE_REQUEST';
export const DESIGN_UPDATE_SUCCESS = 'DESIGN_UPDATE_SUCCESS';
export const DESIGN_UPDATE_FAIL = 'DESIGN_UPDATE_FAIL';

export const DESIGN_UPDATE_RESET = 'DESIGN_UPDATE_RESET';


export const DESIGN_CREATE_REQUEST = 'DESIGN_CREATE_REQUEST';
export const DESIGN_CREATE_SUCCESS = 'DESIGN_CREATE_SUCCESS';
export const DESIGN_CREATE_FAIL = 'DESIGN_CREATE_FAIL';


export const DESIGN_UPDATE_PROFILE_REQUEST = 'DESIGN_UPDATE_PROFILE_REQUEST';
export const DESIGN_UPDATE_PROFILE_SUCCESS = 'DESIGN_UPDATE_PROFILE_SUCCESS';
export const DESIGN_UPDATE_PROFILE_FAIL = 'DESIGN_UPDATE_PROFILE_FAIL';
export const DESIGN_UPDATE_PROFILE_RESET = 'DESIGN_UPDATE_PROFILE_RESET';

export const DESIGN_DETAILS_REQUEST = 'DESIGN_DETAILS_REQUEST';
export const DESIGN_DETAILS_SUCCESS = 'DESIGN_DETAILS_SUCCESS';
export const DESIGN_DETAILS_FAIL = 'DESIGN_DETAILS_FAIL';
export const DESIGN_DETAILS_RESET = 'DESIGN_DETAILS_RESET';



export const DESIGN_LIST_REQUEST = 'DESIGN_LIST_REQUEST';
export const DESIGN_LIST_SUCCESS = 'DESIGN_LIST_SUCCESS';
export const DESIGN_LIST_FAIL = 'DESIGN_LIST_FAIL';

export const DESIGN_DELETE_REQUEST = 'DESIGN_DELETE_REQUEST';
export const DESIGN_DELETE_SUCCESS = 'DESIGN_DELETE_SUCCESS';
export const DESIGN_DELETE_FAIL = 'DESIGN_DELETE_FAIL';
export const DESIGN_DELETE_RESET = 'DESIGN_DELETE_RESET';

export const DESIGN_LOGOUT = 'DESIGN_LOGOUT';


export const DESIGN_TOPSELLERS_LIST_REQUEST = 'DESIGN_TOPSELLERS_LIST_REQUEST';
export const DESIGN_TOPSELLERS_LIST_SUCCESS = 'DESIGN_TOPSELLERS_LIST_SUCCESS';
export const DESIGN_TOPSELLERS_LIST_FAIL = 'DESIGN_TOPSELLERS_LIST_FAIL';   