export const STOCK_SIGNIN_REQUEST = 'STOCK_SIGNIN_REQUEST';
export const STOCK_SIGNIN_SUCCESS = 'STOCK_SIGNIN_SUCCESS';
export const STOCK_SIGNIN_FAIL = 'STOCK_SIGNIN_FAIL';

export const STOCK_UPDATE_REQUEST = 'STOCK_UPDATE_REQUEST';
export const STOCK_UPDATE_SUCCESS = 'STOCK_UPDATE_SUCCESS';
export const STOCK_UPDATE_FAIL = 'STOCK_UPDATE_FAIL';

export const STOCK_UPDATE_RESET = 'STOCK_UPDATE_RESET';


export const STOCK_CREATE_REQUEST = 'STOCK_CREATE_REQUEST';
export const STOCK_CREATE_SUCCESS = 'STOCK_CREATE_SUCCESS';
export const STOCK_CREATE_FAIL = 'STOCK_CREATE_FAIL';


export const STOCK_UPDATE_PROFILE_REQUEST = 'STOCK_UPDATE_PROFILE_REQUEST';
export const STOCK_UPDATE_PROFILE_SUCCESS = 'STOCK_UPDATE_PROFILE_SUCCESS';
export const STOCK_UPDATE_PROFILE_FAIL = 'STOCK_UPDATE_PROFILE_FAIL';
export const STOCK_UPDATE_PROFILE_RESET = 'STOCK_UPDATE_PROFILE_RESET';

export const STOCK_DETAILS_REQUEST = 'STOCK_DETAILS_REQUEST';
export const STOCK_DETAILS_SUCCESS = 'STOCK_DETAILS_SUCCESS';
export const STOCK_DETAILS_FAIL = 'STOCK_DETAILS_FAIL';
export const STOCK_DETAILS_RESET = 'STOCK_DETAILS_RESET';



export const STOCK_LIST_REQUEST = 'STOCK_LIST_REQUEST';
export const STOCK_LIST_SUCCESS = 'STOCK_LIST_SUCCESS';
export const STOCK_LIST_FAIL = 'STOCK_LIST_FAIL';

export const STOCK_DELETE_REQUEST = 'STOCK_DELETE_REQUEST';
export const STOCK_DELETE_SUCCESS = 'STOCK_DELETE_SUCCESS';
export const STOCK_DELETE_FAIL = 'STOCK_DELETE_FAIL';
export const STOCK_DELETE_RESET = 'STOCK_DELETE_RESET';

export const STOCK_LOGOUT = 'STOCK_LOGOUT';


export const STOCK_TOPSELLERS_LIST_REQUEST = 'STOCK_TOPSELLERS_LIST_REQUEST';
export const STOCK_TOPSELLERS_LIST_SUCCESS = 'STOCK_TOPSELLERS_LIST_SUCCESS';
export const STOCK_TOPSELLERS_LIST_FAIL = 'STOCK_TOPSELLERS_LIST_FAIL';   